[project]
name = "idk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.18",
    "matplotlib>=3.10.3",
    "slack-bolt>=1.23.0",
    "xdmod-data>=1.0.3",
]
